### ISSUE TITLE
Angular 4 Issue

### ISSUE THREAD

**Issue by jigarpt** [webfactorymk/ng2-opentok#3]
Hi, 

I am trying to use this library with angular 4. However I am always facing an error like "publisher undefined".

![image](https://user-images.githubusercontent.com/28896871/33433975-bd507f1e-d603-11e7-83ef-7aa0633b33df.png)

Thanks in advance.

**Comment by SnezanaDichevska** [comment]
@jigarpt  This was not an issue from the library, but from the demo. It was not updated to implement the latest version of the library 2.0.0 with breaking changes. However thanks for the notice! It is now fixed, and you can try to use it again (retrieve the new updates from the [demo](https://github.com/webfactorymk/ng2-opentok-demo) first).

**Comment by jigarpt** [comment]
Thanks a ton @SnezanaDichevska . Appreciate your help.

**Comment by SnezanaDichevska** [comment]
@jigarpt you are very welcome. Feel free to give further notice, if you encounter any other problems.
